---
version: '3.4'

services:
  netbox:
    build:
      dockerfile: Dockerfile
      context: .
      args:
        NETBOX_VARIANT: v3.4
    depends_on:
      - postgres
      - redis
    env_file: env/netbox.env
    volumes:
      - ./configuration:/etc/netbox/config:z,ro
    ports:
      - "8000:8080"

  # postgres
  postgres:
    image: postgres:15-alpine
    env_file: env/postgres.env
    ports:
      - "5432:5432"

  # redis
  redis:
    image: redis:6-alpine
    command:
      - sh
      - -c # this is to evaluate the $REDIS_PASSWORD from the env
      - redis-server --appendonly yes --requirepass $$REDIS_PASSWORD ## $$ because of docker-compose
    env_file: env/redis.env
